export const SETTING_ALL_SUMMARY = 'SETTING_ALL_SUMMARY';
export const IS_SORTED = 'IS_SORTED';
export const SETTING_HISTORY = 'SETTING_HISTORY';
export const DELETE_HISTORY = 'DELETE_HISTORY';
export const TOGLE_MODAL = 'TOGLE_MODAL';
export const TOGLE_SPINNER_COUNTRIES = 'TOGLE_SPINNER_COUNTRIES';
export const TOGLE_SPINNER_MODAL = 'TOGLE_SPINNER_MODAL';